# Generated by Django 5.1.5 on 2025-03-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_user_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="files/"),
        ),
    ]
